language: node_js
node_js:
  - "6.2.2" 
sudo: required
os:
  - linux
  - osx

before_install:
  - npm i
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then node_modules/.bin/build -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node_modules/.bin/build -l; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm use ruby-2.0.0-p648; fi
  - zip -r dist.zip dist

deploy:
  provider: releases
  api_key: $TR
  file: dist.zip
  skip_cleanup: true
