language: node_js
node_js:
  - "6.2.2"
os:
  - linux
  - osx


before_install:
  - npm i
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then node_modules/.bin/build -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node_modules/.bin/build -l; fi
  - zip -r dist.zip dist
after_success:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl --ftp-create-dirs -T dist.zip -u $FTP_USER:$FTP_PASSWORD $FTP_URL/phoneTemplate/mac; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl --ftp-create-dirs -T dist.zip -u $FTP_USER:$FTP_PASSWORD $FTP_URL/phoneTemplate/linux; fi
